# -*- coding: utf-8 -*-
"""Ações

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CCj-qzs1UHHsOkS2cAuWQMreXobETrc8

Importando **Bibliotecas**
"""

!pip install yfinance

import yfinance as yf
import pandas as pd
import numpy as np

ativos = ['BOVA11.SA',
'TPIS3.SA',
'AZEV4.SA',
'LUPA3.SA',
'BRAP3.SA',
'AZEV3.SA',
'BRAP4.SA',
'USIM3.SA',
'CSNA3.SA',
'USIM5.SA',
'EUCA4.SA',
'BRSR6.SA',
'BRPR3.SA',
'MDNE3.SA',
'MYPK3.SA',
'PFRM3.SA',
'TECN3.SA',
'CEAB3.SA',
'SYNE3.SA',
'BBAS3.SA',
'ELET6.SA',
'SUZB3.SA',
'CSNA3.SA',
'LUPA3.SA',
'UNIP6.SA',
'ETER3.SA',
'KLBN11.SA',
'KLBN3.SA',
'KLBN4.SA',
'VALE3.SA',
'PTBL3.SA',
'SYNE3.SA',
'BRAP3.SA',
'BRAP4.SA',
'GOAU3.SA',
'GOAU4.SA',
'EALT4.SA',
'CPLE3.SA',
'CPLE6.SA',
'PETR4.SA',
'VALE3.SA',
'BRKM5.SA',
'POSI3.SA',
'EMBR3.SA',
'MRFG3.SA',
'PRIO3.SA',
'PETR3.SA',
'SLCE3.SA',
'JBSS3.SA',
'GGBR4.SA',
'PETR4.SA '
]

inicio = '2021-02-02'
fim = '2022-02-04'

precos = pd.DataFrame()

for i in ativos:
  precos[i] = yf.download(i, start = inicio, end = fim)['Adj Close']



print(precos)

precos.to_excel('ibov.xlsx')

from google.colab import files

files.download('ibov.xlsx')